uploads = []
generated = []

[[outputs]]
id = "_nK-cnlNYsWGlYefJjPrJ"
uri = "file://exports/takipci-paneli-proje.zip"
type = "unspecified"
title = "Takipçi Paneli - Proje Kodu (mevcut hali)"

[[outputs]]
id = "HBuJ40gZ-xc0c22zw5-YT"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-chrome.zip"
type = "unspecified"
title = "Chrome / Edge Eklentisi (.zip)"

[[outputs]]
id = "xfCRxXlAIxGbFcHPgd4ah"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-firefox.zip"
type = "unspecified"
title = "Firefox Eklentisi (.zip)"

[[outputs]]
id = "vdh5kCnXoGi3ATDYjHCVE"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-edge.zip"
type = "unspecified"
title = "Edge Eklentisi"

[[outputs]]
id = "cfpfSIbMCZWa7BOvuF2kU"
uri = "file://artifacts/browser-extension/dist/paneledge.zip"
type = "unspecified"
title = "Edge Eklentisi (paneledge)"
