uploads = []
generated = []

[[outputs]]
id = "_nK-cnlNYsWGlYefJjPrJ"
uri = "file://exports/takipci-paneli-proje.zip"
type = "unspecified"
title = "Takipçi Paneli - Proje Kodu (mevcut hali)"

[[outputs]]
id = "HBuJ40gZ-xc0c22zw5-YT"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-chrome.zip"
type = "unspecified"
title = "Chrome / Edge Eklentisi"

[[outputs]]
id = "xfCRxXlAIxGbFcHPgd4ah"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-firefox.zip"
type = "unspecified"
title = "Firefox Eklentisi"

[[outputs]]
id = "vdh5kCnXoGi3ATDYjHCVE"
uri = "file://artifacts/browser-extension/dist/takipci-paneli-edge.zip"
type = "unspecified"
title = "Edge Eklentisi"

[[outputs]]
id = "cfpfSIbMCZWa7BOvuF2kU"
uri = "file://artifacts/browser-extension/dist/paneledge.zip"
type = "unspecified"
title = "Edge Eklentisi (paneledge)"

[[outputs]]
id = "0YyfJF_Z_Sicr--WrHqQ4"
uri = "file://artifacts/browser-extension/dist/takipci-paneli.zip"
type = "unspecified"
title = "Takipçi Paneli — güncel build"

[[outputs]]
id = "IuA9-sYV_ssUPRNc11vUc"
uri = "file://takipci-paneli.zip"
type = "unspecified"
title = "takipci-paneli.zip"
